In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [11]:
arr = np.array([
    [0, -1],
    [-6, 7]
])

In [12]:
arr

array([[ 0, -1],
       [-6,  7]])

In [13]:
abs_transformer = FunctionTransformer(np.abs, validate = False)
abs_transformer.transform(arr)

array([[0, 1],
       [6, 7]])

In [14]:
def calcuate_squares(x):
    return x * x

In [15]:
squares_transformer = FunctionTransformer(calcuate_squares, validate = False)
squares_transformer.transform(arr)

array([[ 0,  1],
       [36, 49]])

In [16]:
inverse_transformer = FunctionTransformer(inverse_func=np.sqrt, validate = False)
inverse_transformer

FunctionTransformer(accept_sparse=False, check_inverse=True, func=None,
                    inv_kw_args=None, inverse_func=<ufunc 'sqrt'>, kw_args=None,
                    validate=False)

In [20]:
inverse_transformer.inverse_transform(squares_transformer.transform(arr))

array([[0., 1.],
       [6., 7.]])